site_name: Structural Engineering

site_description: A Website for Structural Engineers

#########################################################
# Page Navigation in .yml
#########################################################

nav:
- Home:
   - About Me: index.md
- OpenSEES:
   - OpenSEES User:
      - OpenSEES Seq: opensees/OPS_User/OPS_Seq.md
      - OpenSEES Parallel:
           - OpenSEES df:
                - OpenSEES df:
                   - OpenSEES df:
                        - OpenSEES df:
                            - OpenSEES df:
                                - OpenSEES df: opensees/OPS_User/OPS_Parallel.md
                                - OpenSEES df: opensees/OPS_User/OPS_Parallel.md
                                - OpenSEES df: opensees/OPS_User/OPS_Parallel.md
   - OpenSEES VC++: opensees/OPS_VCpp.md
   - OpenSEES UBUNTU: opensees/OPS_Ubuntu.md
   - OpenSEES Python: opensees/OPS_Python.md
   - OpenSEES Gui: opensees/OPS_GUI.md
   - Tcl/Tk Language: opensees/Tcl_Tk.md
   - MATLAB: opensees/matlab_related.md
   - Python: opensees/Python_Lang.md
   - C++ Libraries and Tools: opensees/Cpp_Lib_Tools.md
- Course Planning:
    - Continuum Mechanics:
         - Introduction: Cont_Mech/Cont_Mech.md
         - Worksheets:
            - Worksheet 1: Cont_Mech/Work_Sheet_1.md
            - Worksheet 2: Cont_Mech/Work_Sheet_2.md
            - Worksheet 3: Cont_Mech/Work_Sheet_3.md
            - Worksheet 4: Cont_Mech/Work_Sheet_4.md
            - Mid-Sem: Cont_Mech/Mid_Sem.md
    - Structural Dynamics: Structural_Dynamics/Structural_Dynamics.md
    - Machine Learning:
        - Introduction: Machine_Learning/Introduction.md
        - Supervised ML: Machine_Learning/Supervised_ML.md
        - Unsupervised ML: Machine_Learning/Unsupervised_ML.md
    - Research Review: Research_Review/Res_review.md
- Misc:
    - UBUNTU OS Related: Misc/UBUNTU_OS_Rel.md
    - Windows OS Related: Misc/Windows_OS_Rel.md
    - Git Related: Misc/Git_Rel.md
    - Really Misc: Misc/Misc.md
    - Uncategorised:
        - Practice: Misc/Practice.md

#########################################################
# Theme Description .yml
#########################################################

theme:
    name: material
    feature:
        tabs: true
    palette:
        primary: 'White'
        accent: 'Red'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'

#########################################################
# Markdown Extensions .yml
#########################################################

markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences
    - codehilite
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

#########################################################
# Javascript Extensions .yml
#########################################################

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Google Analytics
google_analytics: ['UA-148011093-1', 'https://vijaypolimeru.github.io/Something_Abt_Everything/']
